[build]
  publish = "public"
  command = "sed -i s/CSP_NONCE/${CSP_NONCE}/g netlify.toml && npm run build"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-DNS-Prefetch-Control = "off"
    X-Frame-Options = "DENY"
    X-Download-Options = "noopen"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = '''
      default-src 'none';
      style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://fonts.googleapis.com https://d33wubrfki0l68.cloudfront.net;
      script-src 'self' 'nonce-CSP_NONCE' 'unsafe-eval' https://maps.googleapis.com https://d33wubrfki0l68.cloudfront.net;
      font-src https://fonts.gstatic.com;
      base-uri 'self';
      connect-src 'self' https://cdn.jsdelivr.net https://*.googleapis.com https://*.gstatic.com https://d33wubrfki0l68.cloudfront.net;
      manifest-src 'self';
      worker-src 'self';
      img-src 'self' data: https://*.gstatic.com https://*.googleapis.com https://developers.google.com https://*.ggpht.com;
      '''

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, s-maxage=31536000, immutable"
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, s-maxage=31536000, immutable"
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, s-maxage=31536000, immutable"
[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, s-maxage=31536000, immutable"
